### ISSUE TITLE
Too few arguments to function Illuminate\Database\Schema\Grammars\PostgresGrammar::compileAutoIncrementStartingValues()

### ISSUE THREAD

**Issue by SergeyKovtun** [orptech-com/laravel-migration-partition#24]
Trouble with method Schema::createRangePartitioned:24 - not enough argument command in inner call of Builder::compileAutoIncrementStartingValues().
https://github.com/orptech-com/laravel-migration-partition/blob/8906ba7882b2fda71c09a0ca55f1ed4fd06589eb/src/Database/Schema/Grammars/PostgresGrammar.php#L24
Need something like
`$this->compileAutoIncrementStartingValues($blueprint, $command)`

 Also same problem with methods:
 
Schema::compileCreateRangePartition() 
https://github.com/orptech-com/laravel-migration-partition/blob/8906ba7882b2fda71c09a0ca55f1ed4fd06589eb/src/Database/Schema/Grammars/PostgresGrammar.php#L42

 Schema::compileCreateHashPartitioned()
https://github.com/orptech-com/laravel-migration-partition/blob/8906ba7882b2fda71c09a0ca55f1ed4fd06589eb/src/Database/Schema/Grammars/PostgresGrammar.php#L124

**Comment by denizgolbas** [comment]
There is not exist special method yet. 
```php
        DB::statement('CREATE SEQUENCE samples_id_seq START 1 owned by samples.id;');
        DB::statement('ALTER TABLE samples ALTER COLUMN id SET DEFAULT nextval(\'samples_id_seq\'::regclass)');
```

You can call after Schema::create this statements with your real table name (instead of 'samples').

**Comment by ArdaKaraderi** [comment]
Due to inactivity under this issue, I am closing it.
